### PR TITLE
Fixed crash, improved consistency among different screens, fixed use of deprecated method, improved code

### PR DESCRIPTION
**Pull request by PranavPurwar**

### CODE REVIEW

**Comment by PranavPurwar** [comment]
@ilyassesalama

**Comment by ilyassesalama** [comment]
A new major update has been pushed which makes your changes conflict with it. Can you update your codes to match the new changes?

**Comment by PranavPurwar** [comment]
ok, btw you revealed that you're alive \😀

**Comment by ilyassesalama** [comment]
Yeah, I was going to send a message in SWPro server today anyways. Also, I had to push an update here because most of the codes in the repository were obsolete.

**Pull request closed without merging**
